// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/bookmarks": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bookmarks"
                ],
                "summary": "List bookmark",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Halaman",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Item per halaman",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/Model.BaseResponseModel"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "type": "object",
                                            "properties": {
                                                "items": {
                                                    "type": "array",
                                                    "items": {
                                                        "$ref": "#/definitions/Bookmark.BookmarkRes"
                                                    }
                                                },
                                                "limit": {
                                                    "type": "integer"
                                                },
                                                "page": {
                                                    "type": "integer"
                                                },
                                                "pages": {
                                                    "type": "integer"
                                                },
                                                "total": {
                                                    "type": "integer"
                                                }
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Hapus kalau sudah di-bookmark (200), buat kalau belum (201).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bookmarks"
                ],
                "summary": "Toggle bookmark manga",
                "parameters": [
                    {
                        "description": "new_folders.id",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "folder_id": {
                                    "type": "integer"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "folder_id": {
                                    "type": "integer"
                                },
                                "is_bookmarked": {
                                    "type": "boolean"
                                },
                                "message": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "created_at": {
                                    "type": "string"
                                },
                                "folder_id": {
                                    "type": "integer"
                                },
                                "id": {
                                    "type": "integer"
                                },
                                "is_bookmarked": {
                                    "type": "boolean"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/bookmarks/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bookmarks"
                ],
                "summary": "Detail bookmark",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "bookmarks.id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Bookmark.Bookmark"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bookmarks"
                ],
                "summary": "Hapus bookmark",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "bookmarks.id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "message": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/bug-reports": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bug-reports"
                ],
                "summary": "List bug report",
                "parameters": [
                    {
                        "enum": [
                            "all",
                            "open",
                            "fixed"
                        ],
                        "type": "string",
                        "default": "all",
                        "description": "Filter status",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "newest",
                            "oldest"
                        ],
                        "type": "string",
                        "default": "newest",
                        "description": "Urutan",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/Model.BaseResponseModel"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/dto.BugReportItem"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bug-reports"
                ],
                "summary": "Laporkan bug pada manga",
                "parameters": [
                    {
                        "description": "Laporan",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateBugReportRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Model.BaseResponseModel"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/Model.BaseResponseModel"
                        }
                    }
                }
            }
        },
        "/bug-reports/{id}/status": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bug-reports"
                ],
                "summary": "Ubah status bug report",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "bug_reports.id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "status: open|fixed",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateBugReportStatusRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Model.BaseResponseModel"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/Model.BaseResponseModel"
                        }
                    }
                }
            }
        },
        "/duplicates": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "duplicates"
                ],
                "summary": "List kandidat duplikat yang belum direview",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Halaman",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Item per halaman",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "data": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/dto.DuplicateCandidateItem"
                                    }
                                },
                                "page": {
                                    "type": "integer"
                                },
                                "per_page": {
                                    "type": "integer"
                                },
                                "total_data": {
                                    "type": "integer"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/duplicates/backfill": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "duplicates"
                ],
                "summary": "Konversi tabrakan nama lama jadi kandidat duplikat",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/Model.BaseResponseModel"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "$ref": "#/definitions/dto.BackfillResult"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/duplicates/{id}/compare": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "duplicates"
                ],
                "summary": "Bandingkan halaman existing vs incoming",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "duplicate_candidates.id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/Model.BaseResponseModel"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "$ref": "#/definitions/dto.DuplicateCompareResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/Model.BaseResponseModel"
                        }
                    }
                }
            }
        },
        "/duplicates/{id}/resolve": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "action: new_title (butuh new_title), merge (butuh merge_mode replace|append), keep_existing.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "duplicates"
                ],
                "summary": "Selesaikan kandidat duplikat",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "duplicate_candidates.id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Aksi",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ResolveDuplicateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Model.BaseResponseModel"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/Model.BaseResponseModel"
                        }
                    }
                }
            }
        },
        "/export": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/sql"
                ],
                "tags": [
                    "backup"
                ],
                "summary": "Export database (.sql)",
                "parameters": [
                    {
                        "enum": [
                            "full",
                            "data"
                        ],
                        "type": "string",
                        "default": "full",
                        "description": "full = schema+data, data = data saja",
                        "name": "mode",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/Model.BaseResponseModel"
                        }
                    }
                }
            }
        },
        "/export/folders": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "backup"
                ],
                "summary": "Export daftar nama folder di DST_DIR (.json)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/filteredDatas": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "folders"
                ],
                "summary": "Folder staging yang belum selesai",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Model.BaseResponseModel"
                        }
                    }
                }
            }
        },
        "/folders": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "folders"
                ],
                "summary": "List folder di staging (folders)",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Halaman",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Item per halaman",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Model.BaseResponseModel"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Mengembalikan task_id; pantau progres lewat GET /folders/progress/{taskID}.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "folders"
                ],
                "summary": "Pindahkan folder staging ke DST_DIR (async)",
                "parameters": [
                    {
                        "description": "ID folders yang dipindah",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.InputDataReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/Model.BaseResponseModel"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "type": "object",
                                            "properties": {
                                                "task_id": {
                                                    "type": "string"
                                                }
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/folders/delete": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "folders"
                ],
                "summary": "Hapus folder staging (async)",
                "parameters": [
                    {
                        "description": "ID folders yang dihapus",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.InputDataReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/Model.BaseResponseModel"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "type": "object",
                                            "properties": {
                                                "task_id": {
                                                    "type": "string"
                                                }
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/Model.BaseResponseModel"
                        }
                    }
                }
            }
        },
        "/folders/progress/{taskID}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Server-Sent Events: ` + "`" + `progress` + "`" + ` (persen, float), lalu ` + "`" + `done` + "`" + `.",
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "folders"
                ],
                "summary": "Progres move/delete (SSE)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "task_id dari POST /folders atau /folders/delete",
                        "name": "taskID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "event stream",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Task not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/id/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "manga"
                ],
                "summary": "Detail manga + daftar halaman",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "new_folders.id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/Model.BaseResponseModel"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "$ref": "#/definitions/dto.NewFolderResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/Model.BaseResponseModel"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "manga"
                ],
                "summary": "Hapus manga",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "new_folders.id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "apply_to_disk=true juga menghapus folder di DST_DIR",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.DeleteNewFolderRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Model.BaseResponseModel"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "manga"
                ],
                "summary": "Rename manga",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "new_folders.id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Nama baru",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RenameNewFolderRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Model.BaseResponseModel"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/Model.BaseResponseModel"
                        }
                    }
                }
            }
        },
        "/import": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Kirim multipart field ` + "`" + `file` + "`" + `, atau isi SQL mentah sebagai body.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "backup"
                ],
                "summary": "Import database dari file .sql",
                "parameters": [
                    {
                        "type": "file",
                        "description": "File .sql",
                        "name": "file",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Model.BaseResponseModel"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/Model.BaseResponseModel"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "Tukar username/password dengan access token + refresh token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "Kredensial",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/Model.BaseResponseModel"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "$ref": "#/definitions/dto.LoginResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/Model.BaseResponseModel"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/Model.BaseResponseModel"
                        }
                    }
                }
            }
        },
        "/logout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Logout (revoke refresh token)",
                "parameters": [
                    {
                        "description": "Refresh token yang di-revoke",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RefreshRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Model.BaseResponseModel"
                        }
                    }
                }
            }
        },
        "/newFolders": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "manga"
                ],
                "summary": "List manga selesai (new_folders)",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Halaman (20 per halaman)",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Model.BaseResponseModel"
                        }
                    }
                }
            }
        },
        "/refresh": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Refresh access token",
                "parameters": [
                    {
                        "description": "Refresh token",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RefreshRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/Model.BaseResponseModel"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "type": "object",
                                            "properties": {
                                                "access_token": {
                                                    "type": "string"
                                                }
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/Model.BaseResponseModel"
                        }
                    }
                }
            }
        },
        "/search": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "manga"
                ],
                "summary": "Cari manga (new_folders) berdasarkan nama",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Keyword",
                        "name": "q",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Halaman (20 per halaman)",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "data": {
                                    "type": "array",
                                    "items": {
                                        "type": "object"
                                    }
                                },
                                "page": {
                                    "type": "integer"
                                },
                                "per_page": {
                                    "type": "integer"
                                },
                                "total_data": {
                                    "type": "integer"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/translate/pending": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "translate"
                ],
                "summary": "List antrian translate (pending/processing/failed)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/Model.BaseResponseModel"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/dto.PendingTranslationItem"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/translate/settings": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "translate"
                ],
                "summary": "Ambil setting translator (tanpa API key)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/Model.BaseResponseModel"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "$ref": "#/definitions/dto.TranslatorSettingsResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "translate"
                ],
                "summary": "Simpan setting translator",
                "parameters": [
                    {
                        "description": "Setting",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.TranslatorSettingsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Model.BaseResponseModel"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/Model.BaseResponseModel"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "translate"
                ],
                "summary": "Reset setting translator ke default",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Model.BaseResponseModel"
                        }
                    }
                }
            }
        },
        "/translate/settings/worker": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "translate"
                ],
                "summary": "Ambil setting translator untuk worker (termasuk API key)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Model.BaseResponseModel"
                        }
                    }
                }
            }
        },
        "/translate/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "translate"
                ],
                "summary": "Keluarkan manga dari antrian translate",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "new_folders.id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Model.BaseResponseModel"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/Model.BaseResponseModel"
                        }
                    },
                    "409": {
                        "description": "Sedang diproses",
                        "schema": {
                            "$ref": "#/definitions/Model.BaseResponseModel"
                        }
                    }
                }
            }
        },
        "/translate/{id}/complete": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Simpan halaman hasil translate sebagai folder baru di DST_DIR dan tandai request completed.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "translate"
                ],
                "summary": "Upload hasil translate (dipakai worker)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "new_folders.id asal",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Nama folder hasil",
                        "name": "new_folder_name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "file"
                        },
                        "collectionFormat": "multi",
                        "description": "Halaman hasil translate",
                        "name": "files",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/Model.BaseResponseModel"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "type": "object",
                                            "properties": {
                                                "files_skipped": {
                                                    "type": "integer"
                                                },
                                                "files_written": {
                                                    "type": "integer"
                                                },
                                                "name": {
                                                    "type": "string"
                                                },
                                                "new_folder_id": {
                                                    "type": "integer"
                                                }
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/Model.BaseResponseModel"
                        }
                    }
                }
            }
        },
        "/translate/{id}/request": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "translate"
                ],
                "summary": "Masukkan manga ke antrian translate",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "new_folders.id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/Model.BaseResponseModel"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "type": "object",
                                            "properties": {
                                                "status": {
                                                    "type": "string"
                                                }
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/Model.BaseResponseModel"
                        }
                    }
                }
            }
        },
        "/translate/{id}/status": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "translate"
                ],
                "summary": "Update status translate (dipakai worker)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "new_folders.id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "status: pending|processing|completed|failed",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateTranslationStatusRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Model.BaseResponseModel"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/Model.BaseResponseModel"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/Model.BaseResponseModel"
                        }
                    }
                }
            }
        },
        "/update": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Insert folder baru, hapus row yatim, dan antrikan nama yang sudah pernah di-approve ke /duplicates.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "folders"
                ],
                "summary": "Scan SRC_DIR dan sinkronkan tabel folders",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "messages": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/MessageStatus.Message"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/upload/folder": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "upload"
                ],
                "summary": "Upload folder manga ke SRC_DIR",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Nama folder",
                        "name": "folder_name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "file"
                        },
                        "collectionFormat": "multi",
                        "description": "Halaman-halaman (boleh banyak)",
                        "name": "files",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/Model.BaseResponseModel"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "type": "object",
                                            "properties": {
                                                "files_skipped": {
                                                    "type": "integer"
                                                },
                                                "files_written": {
                                                    "type": "integer"
                                                },
                                                "folder_name": {
                                                    "type": "string"
                                                }
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/Model.BaseResponseModel"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "Bookmark.Bookmark": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "folder": {
                    "$ref": "#/definitions/NewFolder.NewFolder"
                },
                "folder_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "Bookmark.BookmarkRes": {
            "type": "object",
            "properties": {
                "bookmark_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "folder_id": {
                    "type": "integer"
                },
                "folder_name": {
                    "type": "string"
                },
                "folder_thumbnail": {
                    "type": "string"
                }
            }
        },
        "MessageStatus.Message": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "folder_name": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "Model.BaseResponseModel": {
            "type": "object",
            "properties": {
                "Code": {
                    "type": "integer"
                },
                "Data": {},
                "HeaderMessage": {
                    "type": "string"
                },
                "Message": {
                    "type": "string"
                }
            }
        },
        "NewFolder.NewFolder": {
            "type": "object",
            "properties": {
                "create_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_completed": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "thumbnail": {
                    "type": "string"
                }
            }
        },
        "dto.BackfillResult": {
            "type": "object",
            "properties": {
                "converted": {
                    "type": "integer"
                },
                "errors": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "dto.BugReportItem": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "folder_id": {
                    "type": "integer"
                },
                "folder_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "thumbnail": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "dto.CreateBugReportRequest": {
            "type": "object",
            "required": [
                "description",
                "folder_id"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "folder_id": {
                    "type": "integer"
                }
            }
        },
        "dto.DeleteNewFolderRequest": {
            "type": "object",
            "properties": {
                "apply_to_disk": {
                    "type": "boolean"
                }
            }
        },
        "dto.DuplicateCandidateItem": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "existing_new_folder_id": {
                    "type": "integer"
                },
                "existing_page_count": {
                    "type": "integer"
                },
                "existing_thumbnail": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "incoming_page_count": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "dto.DuplicateComparePage": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "dto.DuplicateCompareResponse": {
            "type": "object",
            "properties": {
                "existing_pages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.DuplicateComparePage"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "incoming_pages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.DuplicateComparePage"
                    }
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "dto.InputDataReq": {
            "type": "object",
            "properties": {
                "Id": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "dto.LoginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "dto.LoginResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "dto.NewFolderResponse": {
            "type": "object",
            "properties": {
                "create_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_bookmarked": {
                    "type": "boolean"
                },
                "is_completed": {
                    "type": "boolean"
                },
                "is_translated": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "page": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "thumbnail": {
                    "type": "string"
                },
                "translation_error": {
                    "type": "string"
                },
                "translation_status": {
                    "type": "string"
                }
            }
        },
        "dto.PendingTranslationItem": {
            "type": "object",
            "properties": {
                "folder_id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "thumbnail": {
                    "type": "string"
                }
            }
        },
        "dto.RefreshRequest": {
            "type": "object",
            "required": [
                "refresh_token"
            ],
            "properties": {
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "dto.RenameNewFolderRequest": {
            "type": "object",
            "required": [
                "new_name"
            ],
            "properties": {
                "apply_to_disk": {
                    "type": "boolean"
                },
                "new_name": {
                    "type": "string"
                }
            }
        },
        "dto.ResolveDuplicateRequest": {
            "type": "object",
            "required": [
                "action"
            ],
            "properties": {
                "action": {
                    "type": "string"
                },
                "merge_mode": {
                    "type": "string"
                },
                "new_title": {
                    "type": "string"
                }
            }
        },
        "dto.TranslatorSettingsRequest": {
            "type": "object",
            "required": [
                "detection_size",
                "detector",
                "gpu_mode",
                "inpainter",
                "inpainting_precision",
                "inpainting_size",
                "ocr",
                "target_lang",
                "translator"
            ],
            "properties": {
                "api_base": {
                    "type": "string"
                },
                "api_key": {
                    "description": "empty = keep the stored key",
                    "type": "string"
                },
                "api_model": {
                    "type": "string"
                },
                "clear_api_key": {
                    "description": "true = remove the stored key",
                    "type": "boolean"
                },
                "detection_size": {
                    "type": "integer"
                },
                "detector": {
                    "type": "string"
                },
                "gpu_mode": {
                    "type": "string"
                },
                "inpainter": {
                    "type": "string"
                },
                "inpainting_precision": {
                    "type": "string"
                },
                "inpainting_size": {
                    "type": "integer"
                },
                "ocr": {
                    "type": "string"
                },
                "target_lang": {
                    "type": "string"
                },
                "translator": {
                    "type": "string"
                }
            }
        },
        "dto.TranslatorSettingsResponse": {
            "type": "object",
            "properties": {
                "api_base": {
                    "type": "string"
                },
                "api_model": {
                    "type": "string"
                },
                "detection_size": {
                    "type": "integer"
                },
                "detector": {
                    "type": "string"
                },
                "gpu_mode": {
                    "type": "string"
                },
                "has_api_key": {
                    "type": "boolean"
                },
                "inpainter": {
                    "type": "string"
                },
                "inpainting_precision": {
                    "type": "string"
                },
                "inpainting_size": {
                    "type": "integer"
                },
                "is_default": {
                    "type": "boolean"
                },
                "ocr": {
                    "type": "string"
                },
                "target_lang": {
                    "type": "string"
                },
                "translator": {
                    "type": "string"
                }
            }
        },
        "dto.UpdateBugReportStatusRequest": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "status": {
                    "description": "\"open\" | \"fixed\"",
                    "type": "string"
                }
            }
        },
        "dto.UpdateTranslationStatusRequest": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "error_message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Format: ` + "`" + `Bearer \u003caccess_token\u003e` + "`" + `",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Manga Library API",
	Description:      "Backend Go untuk manga library: scan/move folder, bookmark, translate, bug report, duplikat.\nLogin lewat POST /login, lalu klik Authorize dan isi `Bearer <access_token>`.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
